#CFLAGS = -DNDEBUG -O2 -std=c++03  #-ggdb -pedantic-errors -Wall -Werror
CFLAGS = -O2 -std=c++03  #-ggdb -pedantic-errors -Wall -Werror
CFLAGS = -O2 -std=c++03  -ggdb -pedantic-errors -Wall -Werror

all : 
	g++ $(CFLAGS) *.cc -o router

.phony : clean

clean :
	rm -f router
